### PR TITLE
Update epubcheck and epubcheck-adapter

### PR DESCRIPTION
**Pull request by josteinaj**
- Update to working version of org.daisy:epubcheck that uses a newer version of guava
- Change epubcheck-adapter so that it uses org.daisy:epubcheck instead of org.idpf:epubcheck

### CODE REVIEW

**Comment by bertfrees** [comment]
Thanks. Actually I already had prepared some of this in https://github.com/daisy/pipeline-assembly/pull/132, but that's OK. The reason it was pending is because we weren't sure whether we really need the "org.daisy" version. I only did two very small changes. Better would be if we could continue using the official version. In that case romain would need to make a release of it.

**Comment by bertfrees** [comment]
@josteinaj Does this PR block something else?

**Comment by josteinaj** [comment]
@bertfrees I need a working version of epubcheck and epubcheck-adapter for the nordic migrator, and I was getting some errors about the guava version. I'm still having some trouble getting all tests to run in the nordic migrator though; I'm getting a java exception for some of the tests. I will create a regression test for it, and if it turns out to be an issue with epubcheck-adapter or epubcheck I'll create a regression test there also.

If we want to keep using the IDPF-version of epubcheck, which would probably be best, then we need to fix the guava version issue.

@rdeltour: do you know if there's plans to upgrade to guava 15 in epubcheck?

**Comment by bertfrees** [comment]
@rdeltour bump

**Comment by josteinaj** [comment]
I believe I still need this to be able to make a release of the nordic migrator for v1.10.x.

@rdeltour @bertfrees is this on the TODO list?

**Comment by bertfrees** [comment]
@rdeltour Are there plans to upgrade to guava 15 in epubcheck?

**Comment by rdeltour** [comment]
> Are there plans to upgrade to guava 15 in epubcheck?

Not that I know.
If we need it we can create an issue and ask if other contributors/users are OK.

But Guava is now around v24, should we even make a bigger jump?

**Comment by bertfrees** [comment]
OK, v24 makes sense.

**Comment by bertfrees** [comment]
@rdeltour Do you want to create a epubcheck issue?

**Comment by rdeltour** [comment]
> @rdeltour Do you want to create a epubcheck issue?

Done in IDPF/epubcheck#832

**Comment by bertfrees** [comment]
@josteinaj This should have been fixed by https://github.com/daisy/pipeline-scripts-utils/commit/bd16b9b690f9990c40ecb1f932cb3bcb50f1d133 and https://github.com/daisy/pipeline-assembly/commit/0445bdc36870c6bc4d86c2f51079fe7de7afee07. Let me know if I can close this issue.

**Comment by bertfrees** [comment]
@josteinaj I think I can close this issue right?

**Comment by josteinaj** [comment]
Yeah

**Pull request closed without merging**
