### PR TITLE
Fix p:validate-with-xsd

### PR DESCRIPTION
**Pull request by bertfrees**
p:validate-with-xsd is broken in v1.10.2. See https://github.com/daisy/pipeline-scripts/issues/82#issuecomment-325612034. It seems that this was a bug in XMLCalabash.

### CODE REVIEW

**Comment by bertfrees** [comment]
OK. Should we make a bugfix release you think? This makes several scripts unusable.

**Comment by rdeltour** [comment]
> OK. Should we make a bugfix release you think? This bug makes several scripts unusable.

Yes, a bugfix release sound appropriate. We should also figure out why this has passed our user testing and try to avoid that in later releases :-)

**Comment by bertfrees** [comment]
> We should also figure out why this has passed our user testing
See https://github.com/daisy/pipeline-scripts/issues/82#issuecomment-319713202.

**Comment by rdeltour** [comment]
> > We should also figure out why this has passed our user testing
> 
> See daisy/pipeline-scripts#82 (comment).

Doh. Of course 😝

**Comment by bertfrees** [comment]
Merged in:
- https://github.com/daisy/xmlcalabash1/commit/c810bdc0f0
- https://github.com/daisy/pipeline-framework/commit/15a88e579f
- https://github.com/daisy/pipeline-assembly/commit/a6810631be

Other commits (not related to the bug) in this PR were merged in:
- https://github.com/daisy/pipeline-framework/commit/484611094a6bd9da550ee9c9bba7392671b590fd
- https://github.com/daisy/pipeline-build-utils/commit/d289d78b0c
- https://github.com/daisy/pipeline-scripts/commit/79d09660d47072c8ef419b269f5d497ec43f4999
- https://github.com/daisy/pipeline-scripts/commit/58eb1c8430

**Pull request closed without merging**
