### PR TITLE
Update download links for the Web UI to version 2.6.0

### PR DESCRIPTION
**Pull request by josteinaj**

### CODE REVIEW

**Comment by bertfrees** [comment]
@josteinaj Thanks, but could you just add the 2.6.0 release instead of replacing the 2.5.1 release in downloads.yml? And could you update the file sizes (copy from [here](http://repo1.maven.org/maven2/org/daisy/pipeline/webui/2.6.0/))? Also maybe make the links in Installation-and-configuation.md point to http://daisy.github.io/pipeline/Download.html?

**Comment by josteinaj** [comment]
Ok, thanks. Attempt number 2 pushed (also remembered to use subrepo).

**Comment by bertfrees** [comment]
OK, you already updated the web UI wiki? Cool thanks.

**Comment by bertfrees** [comment]
Hold on, I didn't publish it yet. Now I did: http://daisy.github.io/pipeline/Download.html

**Pull request merged**
